[package]
name = "mona"
version = "0.1.0-alpha"
edition = "2021"
authors = ["Larsouille25"]
description = "Mona is an interpreted programming language written in Rust. Run Mona code with the REPL or passing a source file."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive", "cargo"] }
