[package]
name = "mona"
version = "0.1.0"
edition = "2021"
authors = ["Larsouille25"]
description = "Mona is an interpreted programming language written in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
