# Mona is a Ahead Of Time compiled programming language written in Rust, the code generation and compilation is made with LLVM. 

[workspace]

members = [
    "mona_fe",
    "mona_common",
    "mona_codegen",
    "mona_build",
    "mona",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Larsouille25"]
readme = "README.md"

[workspace.dependencies]
inkwell = { version = "0.2.0", default-features = false }
clap = { version = "4.3.0", features = ["derive", "cargo"] }

criterion = "0.5.0"