# Mona is an interpreted programming language written in Rust. Run Mona code with the REPL or passing a source file.

[workspace]

members = [
    "mona_fe",
    "mona_common",
    "mona_codegen",
    "mona_build",
    "mona",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Larsouille25"]
readme = "README.md"

[workspace.dependencies]
inkwell = { version = "0.2.0", default-features = false }
clap = { version = "4.3.0", features = ["derive", "cargo"] }

[workspace.dev-dependencies]
criterion = "0.5.0"