on:
  release:
    types: [published]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Criterion benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly
      
      - name: Run benchmark
        run: cargo +nightly bench
      - name: List files & pwd
        run: ls && pwd
        
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@Larsouille25'
