
name: Rust tests

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: "Test on ${{ matrix.os }} with LLVM ${{ matrix.llvm-version[0] }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - [ubuntu-latest]
          - [windows-latest]
          - [macos-latest]
        llvm-version:
          - ["13.0", "13-0"]
          - ["14.0", "14-0"]
          - ["15.0", "15-0"]
          - ["16.0", "16-0"]
    steps:
    - uses: actions/checkout@v3

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.3.0

    - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8
        with:
          version: ${{ matrix.llvm-version[0] }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
